global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'hotelmind-backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'hotelmind-ml-backend'
    static_configs:
      - targets: ['ml-backend:8000']
